# Generated by Django 3.2.12 on 2022-03-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='backlogs',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='district',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='highersecondary_percentage',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='highschool_percentage',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='state',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='university',
        ),
    ]
