# Generated by Django 4.0 on 2022-03-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ctgry_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='dept_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
