# Generated by Django 4.0 on 2022-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_question_ctgry_id_question_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='time_taken',
            field=models.IntegerField(),
        ),
    ]
